### ISSUE TITLE
Running multiple instances of Cookiecutter-Django-React-Vite  on one server

### ISSUE THREAD

**Issue by vicwiller** [Painkiller995/Cookiecutter-Django-React-Vite#1]
I used your template and I love it! Thank you so much!

What would be great is running multiple instances on one server.

Have you done that yourself?

How would you go about it?

Removing traefik from the project and have one seperate traefik instance one the server which handles all projects would be an option but I am not sure how to configure that.

What are your thoughts?

**Comment by Painkiller995** [comment]
Hi,

Disregard Traefik and consider it as a project-based layer. For each instance, you have an independent reverse proxy.

If I want to do it myself, I would like to use a higher-level Traefik or Nginx container, which will redirect to each instance using **domains** or **locations**. Here's an example:

docker-compose.yml
```yaml
version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx_reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - project1_net
      - project2_net
    restart: always

networks:
  project1_net:
    external: true # Telling Docker that the network is created outside of the current compose
    name: project_1_project1_net
  project2_net:
    external: true
    name: project_2_project2_net
```

nginx.conf
```nginx
http {
    server {
        listen 80;
        listen 443;
        server_name my_server;

        location /project1 {
            proxy_pass http://project_1_local_traefik:443;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /project2 {
            proxy_pass http://project_2_local_traefik:443;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }    
    } 
}
```

When you visit localhost:443/project1, you are accessing project 1. The same goes for the other projects.
This method makes it simple to add or remove projects. You can also use Traefik for this purpose.
